steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -f
  - app/Dockerfile
  - -t
  - asia-southeast1-docker.pkg.dev/opjt-gitaiops-project/notiflex/api:v0.1.0
  - .
images:
- asia-southeast1-docker.pkg.dev/opjt-gitaiops-project/notiflex/api:v0.1.0
