apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: notiflex-api
  namespace: enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notiflex-api
  template:
    metadata:
      labels:
        app: notiflex-api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: api-pool
      containers:
      - name: api
        image: asia-southeast1-docker.pkg.dev/opjt-gitaiops-project/notiflex/api:sha-6a8de73
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VALKEY_ADDR
          value: valkey-primary.notiflex.svc.cluster.local:6379
        - name: VALKEY_PASSWORD_FILE
          value: /mnt/secrets/valkey-password
        volumeMounts:
        - name: secrets
          mountPath: /mnt/secrets
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: secrets
        secret:
          secretName: valkey-enterprise
  strategy:
    canary:
      canaryService: notiflex-api-preview
      stableService: notiflex-api
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
